### ISSUE TITLE
Xo Server does not start after upgrade

### ISSUE THREAD

**Issue by mrnaz** [Jarli01/xenorchestra_updater#48] opened 2021-06-07 09:21 UTC
#### Expected Behavior

XO Server should start

-----

#### Actual Behavior

XO Server does not start

-----

#### Confirm XOCE services are running

```systemctl status xo-server.service```

It is not running

#### Provide the output of journalctl logs

```journalctl -u xo-server -f -n 50```
 
Jun 07 18:39:54 xoa-HVM-domU systemd[1]: Started XO Server.
Jun 07 18:39:55 xoa-HVM-domU xo-server[2709]: (node:2709) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
Jun 07 18:39:55 xoa-HVM-domU xo-server[2709]: (Use `node --trace-warnings ...` to show where the warning was created)
Jun 07 18:39:55 xoa-HVM-domU xo-server[2709]: /opt/xen-orchestra/packages/xo-server/dist/xapi/mixins/index.js:2
Jun 07 18:39:55 xoa-HVM-domU xo-server[2709]: import _gpu, * as __gpu from "./gpu";
Jun 07 18:39:55 xoa-HVM-domU xo-server[2709]: ^^^^^^
Jun 07 18:39:55 xoa-HVM-domU xo-server[2709]: SyntaxError: Cannot use import statement outside a module
Jun 07 18:39:55 xoa-HVM-domU xo-server[2709]:     at wrapSafe (internal/modules/cjs/loader.js:984:16)
Jun 07 18:39:55 xoa-HVM-domU xo-server[2709]:     at Module._compile (internal/modules/cjs/loader.js:1032:27)
Jun 07 18:39:55 xoa-HVM-domU xo-server[2709]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
Jun 07 18:39:55 xoa-HVM-domU xo-server[2709]:     at Module.load (internal/modules/cjs/loader.js:933:32)
Jun 07 18:39:55 xoa-HVM-domU xo-server[2709]:     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
Jun 07 18:39:55 xoa-HVM-domU xo-server[2709]:     at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
Jun 07 18:39:55 xoa-HVM-domU xo-server[2709]:     at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
Jun 07 18:39:55 xoa-HVM-domU xo-server[2709]:     at async Loader.import (internal/modules/esm/loader.js:177:24)
Jun 07 18:39:55 xoa-HVM-domU xo-server[2709]:     at async Object.loadESM (internal/process/esm_loader.js:68:5)
Jun 07 18:39:55 xoa-HVM-domU systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Jun 07 18:39:55 xoa-HVM-domU systemd[1]: xo-server.service: Failed with result 'exit-code'.
Jun 07 18:39:56 xoa-HVM-domU systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 5.
Jun 07 18:39:56 xoa-HVM-domU systemd[1]: Stopped XO Server.
Jun 07 18:39:56 xoa-HVM-domU systemd[1]: xo-server.service: Start request repeated too quickly.
Jun 07 18:39:56 xoa-HVM-domU systemd[1]: xo-server.service: Failed with result 'exit-code'.
Jun 07 18:39:56 xoa-HVM-domU systemd[1]: Failed to start XO Server.

#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
Upgrade

- Version of XOCE server and web interface you're running
5.81.0 I was trying to update to 5.81.1

- What OS is XOCE running on?
Xubuntu 21.04

- What method you used to install XOCE (xo_install.sh, manual installation, etc)
xo_install.sh

- What specific XOCE page you're on, and what specific element you're interacting with to trigger the error
The server does not start, so there is no page to show an error.

- If a stacktrace is provided in the error, include that too.
n/a

- Any errors that appear in your browser's error console.
n/a

- Include what you've done so far in the installation, and if you got any error messages along the way.
I ran the installer, and then did not run any commands until I ran the update script.

- Indicate whether or not you've manually edited any data directly.
I did not, I just ran the script commands as-is from the instructions.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by gsloop** [comment] 2021-06-07 21:37
I'm getting the same base error:  

xo-server[1423]: (node:1423) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
xo-server[1423]: (Use `node --trace-warnings ...` to show where the warning was created)
xo-server[1423]: /opt/xen-orchestra/packages/xo-server/dist/xapi/mixins/index.js:2
xo-server[1423]: import _gpu, * as __gpu from "./gpu";
xo-server[1423]: ^^^^^^
xo-server[1423]: SyntaxError: Cannot use import statement outside a module

Running Ubuntu 18.04
Ubuntu 18.04 (Not sure what version of XOA I was on. - I should have checked before I rolled. I update occasionally - I'd guess 6 mos ago or more.)
Using: sudo curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/master/xo-update.sh | bash

Also did a force rebuild:
sudo curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/master/xo-update.sh | bash -s -- -f 
Still in the same state.

No manual edits of anything.

**Comment by Danp2** [comment] 2021-06-07 22:06
Please post the output from `node -v`

**Comment by gsloop** [comment] 2021-06-07 23:33
# node -v
v14.17.0

**Comment by mrnaz** [comment] 2021-06-08 00:04
v14.16.1

**Comment by Danp2** [comment] 2021-06-08 00:36
@mrnaz What do you get from `n --lts`? We recently updated the script so that it should abort if the installed version of Node isn't the LTS version. XO now requires at least v14.17, so you'll need to update Node to the latest LTS version. This can be accomplished with `sudo n lts`

But like I said, the script should have compared the versions and aborted, so we need to figure out why that didn't happen.

@gsloop Have you reviewed [this thread](https://xcp-ng.org/forum/topic/4630/syntaxerror-cannot-use-import-statement-outside-a-module)?

**Comment by gsloop** [comment] 2021-06-08 00:59
I hadn't seen that thread - so I looked through it, and there doesn't seem to be anything relevant to my install...

I can't find any .js files - mine are all mjs - and no reference to any index.js files.
(Of course, I have no real idea what I'm doing here, so it's totally possible I'm missing something stupid.)

So, I'm baffled.
Is there a way to build again from scratch, and still keep my old XOA config/setup? (Perhaps that won't fix anything either, but thought it might be worth a try.)

**Comment by Danp2** [comment] 2021-06-08 01:06
@gsloop Yes, you should be able to completely remove the \opt\xenorchestra directory and then rerun the installer script.

**Comment by gsloop** [comment] 2021-06-08 03:55
That worked fine. Back up!
Thanks! 
So much!

**Comment by Danp2** [comment] 2021-06-10 18:24
@mrnaz It's been a few days. Any progress on your end?

**Comment by Jarli01** [comment] 2021-06-12 11:43
@mrnaz did you still need help?

**Comment by hrvoj3e** [comment] 2021-06-15 07:03
My fix was

```shell
## backup
tar -czf /opt/xen-orchestra.tgz /opt/xen-orchestra/
## remove
rm -rf /opt/xen-orchestra/
## install again
bash xo_install.sh
```

Same problem
 - https://github.com/vatesfr/xen-orchestra/issues/5784

**Comment by Jarli01** [comment] 2021-06-15 13:32
So a clean install resolved it, appears to be an upstream issue. 

Closing for now as there is a clear and simple fix.

**Comment by Danp2** [comment] 2021-06-15 14:55
I wouldn't describe it as an upstream issue. It's more like a "dirty" build directory where there are some leftover files that shouldn't be there. I wonder if `rm -rf dist` followed by `yarn; yarn build` would solve the issue?

**Comment by gsloop** [comment] 2021-06-15 15:17
I have another couple of installs I will need to upgrade at some point. While I'm not certain they are all identical, I think they are...

I'd be glad to try some "stuff" if someone wants to give me instructions - like you'd give a five year old. :) 
['Cause I got no idea what the hell I'm doing with yarn etc.]

I can report what I find.

**Comment by Danp2** [comment] 2021-06-15 15:27
@gsloop Appreciate the offer. This is what I would recommend --

- Take a snapshot before attempting upgrade
- Then perform the normal upgrade process
- Check the logs (`journalctl -u xo-server -f -n 50`) post upgrade
- If it fails as above, then try the following steps
```
sudo bash
 cd \opt\xenorchestra
 rm -rf dist
 yarn; yarn build
 sudo systemctl restart xo-server.service
 ```
- Check the logs again
- Report back ;-)

**Comment by gsloop** [comment] 2021-06-15 15:36
I'll see when I can get to those, but it might be a while - days to weeks.
Just setting expectations...in case it matters.

**Comment by kruess** [comment] 2021-06-17 15:57
As I am suffering the same way (Ubuntu LTS 20.04.2, Node version 14.17.1, upgraded from xo-server 5.79.3/xo-web 5.81.0), I went through the yarn commands, but it did not change the behaviour, the service still cannot be started with the same error.

**Comment by Danp2** [comment] 2021-06-17 16:24
@kruess So you ran the `rm -rf dist` before rebuilding with yarn?

**Comment by kruess** [comment] 2021-06-17 16:40
Correct, but that directory was not even existing.

What fixed it was hrvoj3e's suggestion to delete /opt/xen-orchestra and re-run xo-install.sh

**Comment by Jarli01** [comment] 2021-06-17 16:52
> Correct, but that directory was not even existing.
> 
> What fixed it was hrvoj3e's suggestion to delete /opt/xen-orchestra and re-run xo-install.sh

For the record we've previously offered this as an option and points to the discard able nature of XO. Just reinstall and move on.

**Comment by Danp2** [comment] 2021-06-17 17:39
FWIW, the command `rm -rf dist` should recursively search the directory tree and remove any folders with the name `dist`.

**Comment by kruess** [comment] 2021-06-18 05:45
Based on my understanding, <rm -rf dist> will only delete the file or directory 'dist' in the current directory and it will also delete the directory, if it is not empty.

**Comment by Danp2** [comment] 2021-06-18 11:00
@kruess Ok... guess I misunderstood what it was supposed to do. I wonder if this would work?
```
cd /opt/xen-orchestra/packages/xo-server/
rm -rf dist
cd /opt/xen-orchestra
yarn; yarn build
```

**Comment by kruess** [comment] 2021-06-19 11:17
@Danp2 Okay, I went back to the snapshot before the update (xo-server 4.79.3, xo-web 5.81.0) and ran the xo-update.sh, again (this time i ignored the ubuntu updates). It nodded about the node version and so I executed <n lts> and the next xo-update.sh went through. The above error then was present and I executed your <rm/yarn> commands and restarted the xo-server.service, but it failed, again. Same error as above about the import syntax error.

**Comment by Danp2** [comment] 2021-06-19 15:56
@kruess Try this if you get a chance --
```
cd /opt/xen-orchestra
rm -rf /opt/xen-orchestra/packages/xo-server/dist
yarn; yarn build
sudo systemctl restart xo-server.service
```

**Comment by kruess** [comment] 2021-06-19 21:31
That's exactely what I did before - just with a different working directory and full path for the 'rm' command while deleting /opt/xen-orchestra/packages/xo-server/dist .

**Comment by ClintDavis** [comment] 2021-06-25 12:48
Had to remove the untracked files to get it working.
The update script could perhaps perform that or warn about that.

**Comment by kruess** [comment] 2021-06-25 15:06
Which untracked files?

**Comment by Danp2** [comment] 2021-06-25 15:14
> Had to remove the untracked files to get it working.

That's what this line is supposed to be doing --

`git diff-index --quiet HEAD -- || git stash -u && git stash drop`

**Comment by ClintDavis** [comment] 2021-06-29 10:10
```
root@fj-xoa-ce:~# cd /opt/xen-orchestra/
root@fj-xoa-ce:/opt/xen-orchestra# git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        @xen-orchestra/proxy/src/app/mixins/index.js
        packages/xo-server/src/api/index.js
        packages/xo-server/src/xapi/mixins/index.js
        packages/xo-server/src/xo-mixins/index.js

nothing added to commit but untracked files present (use "git add" to track)
root@fj-xoa-ce:/opt/xen-orchestra# ls -lh packages/xo-server/src/api/index.js
-rw-r--r-- 1 root root 5.3K Mar 28 06:30 packages/xo-server/src/api/index.js
root@fj-xoa-ce:/opt/xen-orchestra# git diff-index --quiet HEAD -- || git stash -u && git stash drop
No stash entries found.
root@fj-xoa-ce:/opt/xen-orchestra# git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        @xen-orchestra/proxy/src/app/mixins/index.js
        packages/xo-server/src/api/index.js
        packages/xo-server/src/xapi/mixins/index.js
        packages/xo-server/src/xo-mixins/index.js

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by ClintDavis** [comment] 2021-06-29 10:20
```
root@fj-xoa-ce:/opt/xen-orchestra# git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        @xen-orchestra/proxy/src/app/mixins/index.js
        packages/xo-server/src/api/index.js
        packages/xo-server/src/xapi/mixins/index.js
        packages/xo-server/src/xo-mixins/index.js

nothing added to commit but untracked files present (use "git add" to track)
root@fj-xoa-ce:/opt/xen-orchestra# git stash --include-untracked
Saved working directory and index state WIP on master: 3d15a73f1 feat(xo-web/vm/new disk): generate random name (#5828)
root@fj-xoa-ce:/opt/xen-orchestra# git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

Not a problem for me anymore, as I was able to work past it, but just in case others are stuck.

**Comment by Danp2** [comment] 2021-06-29 11:36
Hmmm..... I wonder what causes this issue. ☹️  Looks like `git clean` is the solution.

**Comment by Danp2** [comment] 2021-06-29 11:54
I just pushed an update that should automatically delete these untracked files. Here's the command if anyone wants to test --

```curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/dp_untrackedfix/xo-update.sh | sudo bash```

**Comment by ClintDavis** [comment] 2021-06-29 13:43
I managed to work out more from a snapshot I took before my upgrade, I reverted and checked the repo, the only untracked file is the yarn.lock file.

These files show up as untracked *after* the update script runs:
@xen-orchestra/proxy/src/app/mixins/index.js
packages/xo-server/src/api/index.js
packages/xo-server/src/xapi/mixins/index.js
packages/xo-server/src/xo-mixins/index.js

So when the clean occurs, these files are not present.

**Comment by Danp2** [comment] 2021-06-29 13:50
@ClintDavis Interesting. We could always move the clean to later in the process.

**Comment by Danp2** [comment] 2021-06-29 17:10
@ClintDavis I moved the command until after the `git pull`. Are you able to test again to see if the result is better?

**Comment by ClintDavis** [comment] 2021-06-30 03:58
@Danp2, yes that worked.

**Closed** 2021-06-30 22:04 UTC

**Comment by kruess** [comment] 2021-07-01 09:57
I can confirm that updating now does not cause this problem, anymore. Furthermore, updating a broken XOA installation fixes the problem and the xo-server can be started without problems after updating.
